### ISSUE TITLE
Baseline (IDE) accuracy 1% off

### ISSUE THREAD

**Issue by dajung1125** [zhunzhong07/CamStyle#10]
Hello, 
Thanks for sharing the code!
I ran your code without any modification for re-id baseline without using camstyle.
I was only able to get 84.3% instead of 85.6% in Readme.

Is there any other hyperparameter setting that I have to change to achieve 85% accuracy for baseline IDE?
Any idea where that 1 % gap comes from?

Thank you!

**Comment by zhunzhong07** [comment]
You can try to run the baseline several times, each result will have about 1% float in rank-1 accuracy.

**Comment by dajung1125** [comment]
Could you tell me how many trials did you average over to get that number? (As well as your result)

**Comment by zhunzhong07** [comment]
In my experiment, I achieve this accuracy every three times.
