### ISSUE TITLE
a error on my computer

### ISSUE THREAD

**Issue by jian-xu** [zhunzhong07/CamStyle#2]
aaron@PC:~/reid/CamStyle$ python main.py -d market --logs-dir logs/market-ide
Market dataset loaded
  subset   | # ids | # images
  ---------------------------
  train    |     0 |        0
  query    |     0 |        0
  gallery  |     0 |        0
  camstyle  |     0 |        0
Traceback (most recent call last):
  File "main.py", line 198, in <module>
    main(parser.parse_args())
  File "main.py", line 138, in main
    trainer.train(epoch, train_loader, optimizer)
  File "/home/aaron/reid/CamStyle/reid/trainers.py", line 28, in train
    for i, inputs in enumerate(data_loader):
  File "/home/aaron/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 417, in __iter__
    return DataLoaderIter(self)
  File "/home/aaron/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 242, in __init__
    self._put_indices()
  File "/home/aaron/anaconda3/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 290, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/aaron/anaconda3/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 119, in __iter__
    for idx in self.sampler:
  File "/home/aaron/anaconda3/lib/python3.5/site-packages/torch/utils/data/sampler.py", line 50, in __iter__
    return iter(torch.randperm(len(self.data_source)).long())
RuntimeError: invalid argument 1: must be strictly positive at /opt/conda/conda-bld/pytorch_1523242347739/work/torch/lib/TH/generic/THTensorMath.c:2247
......
when I ran 'python main.py -d market --logs-dir logs/market-ide' on my computer,  I got the information above, so I checked the code. I found in the line 36 of evaluators.py, you used 'for i, (imgs, fnames, pids, _) in enumerate(data_loader):' to process the data_loader, while in line 28 of trainers.py you used 'for i, inputs in enumerate(data_loader):', then you defined a function named _parse_data to process this 'inputs', then I got the error. So I was wondering if you have the same problem, and am I supposed to change the code there?
(I tried on pytorch 0.3.1 on both python 3.5 and python 3.6, and also I thought maybe it was my pytorch's problem?

**Comment by zhunzhong07** [comment]
It seems that you did not put the market dataset under the right path. Please follow the preparation instruction in README.

**Comment by jian-xu** [comment]
Sorry, that's my fault. Thanks for your reply and also your work on Camstyle,  random erasing and re-ranking which helps me a lot. And it seems like you offered the generated fake image, and I would like to know how to generate these images in detail. (since you added some modification which is identity mapping loss on CycleGAN and as a beginner I thought I am not capable of reproduce your work)

**Comment by zhunzhong07** [comment]
The identity loss is included in CycleGAN, so you can use the pytorch version of CycleGAN to reproduce CamStyle. Specifically, you need to train camera style transfer models for each pair of cameras.

**Comment by jian-xu** [comment]
Thank you very much and wish you well.
