### ISSUE TITLE
请问您的GAN模型是用什么数据训练的呢？也是用market和duke吗？

### ISSUE THREAD

**Issue by songning2018** [zhunzhong07/CamStyle#5]

**Comment by songning2018** [comment]
market和duke数据集的统一性人在不同摄像头下的姿态和衣着有可能不同，能使用这样的数据来训练GAN吗

**Comment by zhunzhong07** [comment]
We use market and duke to train camera style transfer models, please see our paper for details.

**Comment by 2110317008** [comment]
> We use market and duke to train camera style transfer models, please see our paper for details.

当你训练GAN时，数据格式是怎么放置的？
挑选出camera1的一张图片为cycleGAN里面的trainA，然后再选出camera2.3.4.5.6中的图像为cycleGAN数据格式里面的trainB？
